name: Push to DingTalk V5

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
  # 每天早上 2点（东8区，所以需要-8小时，为 18 ） 拉取最新数据
  schedule:
  - cron: "0 18 * * *"

jobs:
  dingtalk:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i
    - run: npm run dingtalk
      env:
        DINGTALK_ROBOT_URL: ${{secrets.DINGTALK_ROBOT_URL}}
        SHEETS_CLIENT_EMAIL: ${{secrets.SHEETS_CLIENT_EMAIL}}
        SHEETS_PRIVATE_KEY: ${{secrets.SHEETS_PRIVATE_KEY}}
        SHEETS_PRIVATE_KEY_ID: ${{secrets.SHEETS_PRIVATE_KEY_ID}}

