name: Push Real Estate Info to DingTalk

on:
  push:
    branches: [ $default-branch ]
  # 每天早上 1点30分 拉取最新数据
  schedule:
  # - cron: "30 1 * * *"
  # 每分钟执行，用于测试
  - cron: "*/1 * * * *"

jobs:
  dingtalk:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm run dingtalk